# Generated by Django 5.2 on 2025-11-29 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_number', models.CharField(max_length=20, unique=True)),
                ('origin', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('in_transit', 'In Transit'), ('delayed', 'Delayed'), ('arrived', 'Arrived')], default='in_transit', max_length=20)),
                ('depart_time', models.DateTimeField()),
                ('distance_km', models.PositiveIntegerField(help_text='Estimated route distance in km')),
                ('avg_speed_kmh', models.PositiveIntegerField(default=30, help_text='Average speed for ETA calc')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Website',
        ),
    ]
