# Generated by Django 5.2 on 2025-11-29 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_container_delete_website'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='container',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='container',
            name='avg_speed_kmh',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='container',
            name='distance_km',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='container',
            name='status',
            field=models.CharField(choices=[('in_transit', 'In Transit'), ('delayed', 'Delayed'), ('arrived', 'Arrived')], max_length=20),
        ),
    ]
