# Generated by Django 5.2 on 2025-11-29 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_remove_container_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='container',
            name='avg_speed_kmh',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='container',
            name='distance_km',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='container',
            name='status',
            field=models.CharField(choices=[('in_transit', 'In Transit'), ('delayed', 'Delayed'), ('arrived', 'Arrived')], default='in_transit', max_length=20),
        ),
    ]
